function updateSafetyUi(){cleanExpiredTrash();$('trashCount').textContent=trash.length;const last=safeRead(LAST_CLEAR_KEY,null);$('restoreBtn').disabled=!(last?.rows?.length);saveState()}
function render(){const list=$('list');$('count').textContent=rows.length;if(!rows.length){list.innerHTML='<div id="empty" class="empty"><div class="emptyicon"><span class="material-symbols-rounded">person_search</span></div><strong>Todavía no hay leads</strong><span>Pegá una captura o un texto para comenzar.</span></div>';updateSafetyUi();return}list.innerHTML=rows.map((r,i)=>{let c=CareerMapper[r.tecnicaturaId],opts='<option value="">Sin asignar</option>'+Object.entries(CareerMapper).map(([id,x])=>`<option value="${id}" ${String(r.tecnicaturaId)===id?'selected':''}>${esc(x.label)}</option>`).join('');return `<div class="lead"><div class="bar" style="background:${c?.color||'#cbd5e1'}"></div><div class="leadbody"><div class="leadtop"><span class="leadnum">LEAD ${rows.length-i}</span><div class="leadtools"><button class="iconbtn copy" title="Copiar lead" onclick="copyOne('${r.id}')"><span class="material-symbols-rounded">content_copy</span></button><button class="iconbtn delete" title="Mover a papelera" onclick="del('${r.id}')"><span class="material-symbols-rounded">delete</span></button></div></div><div class="grid"><div class="cell"><div class="ct"><span>Nombre</span>${badge(r.meta?.name)}</div><input class="name" value="${esc(r.nombre)}" onchange="upd('${r.id}','nombre',this.value)"></div><div class="cell"><div class="ct"><span>Teléfono</span>${badge(r.telefono?'alta':'baja')}</div><input value="${esc(fmtPhone(r.telefono))}" onchange="upd('${r.id}','telefono',this.value)"></div><div class="cell"><div class="ct"><span>Correo</span>${badge(r.email?'alta':'baja')}</div><input value="${esc(r.email)}" placeholder="Sin correo" onchange="upd('${r.id}','email',this.value)"></div><div class="cell"><div class="ct"><span>Carrera</span>${badge(r.meta?.career)}</div><select onchange="upd('${r.id}','tecnicaturaId',this.value)">${opts}</select></div><div class="cell"><div class="ct"><span>Fuente</span></div><select onchange="upd('${r.id}','fuente',this.value)">${['WhatsApp Comercial','Correo','Facebook / Instagram','Web','Otro'].map(x=>`<option ${r.fuente===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="cell"><div class="ct"><span>Provincia</span></div><input value="${esc(r.provincia)}" onchange="upd('${r.id}','provincia',this.value)"></div></div><div class="obsrow"><input value="${esc(r.observaciones)}" placeholder="📝 Observaciones" onchange="upd('${r.id}','observaciones',this.value)"></div></div></div>`}).join('');updateSafetyUi()}
function upd(id,f,v){let r=rows.find(x=>String(x.id)===String(id));if(!r)return;if(f==='nombre')v=title(v);if(f==='telefono'){v=v.replace(/\D/g,'');r.provincia=province(v)}r[f]=v;saveState();cloudUpsertLead(r);render()}
function del(id){const idx=rows.findIndex(x=>String(x.id)===String(id));if(idx<0)return;const [item]=rows.splice(idx,1),entry=newTrashEntry(item,'individual');trash.unshift(entry);saveState();cloudDeleteLead(item.id);cloudUpsertTrash(entry);render();toast('Lead enviado a Papelera')}
function clearAll(){if(!rows.length)return toast('No hay leads para limpiar');const total=rows.length;if(!confirm(`¿Seguro que querés limpiar ${total} lead(s)?\n\nSe guardará una copia y podrás restaurarlos desde "Restaurar última limpieza" o la Papelera durante 30 días.`))return;createBackup('Antes de limpiar');const snapshot=JSON.parse(JSON.stringify(rows)),clearBatchId='clear_'+Date.now();localStorage.setItem(LAST_CLEAR_KEY,JSON.stringify({createdAt:Date.now(),rows:snapshot,clearBatchId}));const entries=snapshot.map(item=>newTrashEntry(item,'limpieza',clearBatchId));trash.unshift(...entries);rows=[];saveState();snapshot.forEach(item=>cloudDeleteLead(item.id));entries.forEach(cloudUpsertTrash);render();toast(`${total} lead(s) enviados a Papelera`)}
function restoreLastClear(){const last=safeRead(LAST_CLEAR_KEY,null);if(!last?.rows?.length)return toast('No hay una limpieza para restaurar');const existing=new Set(rows.map(x=>String(x.id))),restore=last.rows.filter(x=>!existing.has(String(x.id)));rows=[...restore,...rows];const restoredIds=new Set(restore.map(x=>String(x.id))),removed=trash.filter(x=>x.reason==='limpieza'&&((last.clearBatchId&&x.clearBatchId===last.clearBatchId)||restoredIds.has(String(x.item?.id))));trash=trash.filter(x=>!removed.includes(x));localStorage.removeItem(LAST_CLEAR_KEY);saveState();restore.forEach(cloudUpsertLead);removed.forEach(cloudDeleteTrash);render();toast(`${restore.length} lead(s) restaurados`)}
function openTrash(){renderTrash();$('trashModal').classList.add('show')}
function closeTrash(){$('trashModal').classList.remove('show')}
function renderTrash(){cleanExpiredTrash();$('trashCount').textContent=trash.length;const box=$('trashList');if(!trash.length){box.innerHTML='<div class="empty" style="height:180px"><div class="emptyicon"><span class="material-symbols-rounded">delete_sweep</span></div><strong>La papelera está vacía</strong><span>No hay elementos para restaurar.</span></div>';saveState();return}box.innerHTML=`<div style="display:flex;justify-content:flex-end;gap:7px;margin-bottom:10px"><button class="btn outlined" onclick="restoreAllTrash()"><span class="material-symbols-rounded">restore</span><span>Restaurar todo</span></button><button class="btn danger-soft" onclick="emptyTrash()"><span class="material-symbols-rounded">delete_forever</span><span>Vaciar papelera</span></button></div>`+trash.map((t,i)=>{const r=t.item||{},d=new Date(t.deletedAt||Date.now()).toLocaleString('es-AR');return `<div class="trashitem"><div><strong>${esc(r.nombre||'SIN NOMBRE')}</strong><small>${esc(fmtPhone(r.telefono||''))}${r.email?' · '+esc(r.email):''}<br>Eliminado: ${d}</small></div><div class="trashactions"><button class="btn outlined" onclick="restoreTrashItem(${i})"><span class="material-symbols-rounded">restore</span><span>Restaurar</span></button><button class="btn danger-soft" onclick="deleteTrashItem(${i})"><span class="material-symbols-rounded">delete_forever</span><span>Eliminar</span></button></div></div>`}).join('');saveState()}
function restoreTrashItem(i){const t=trash[i];if(!t)return;const exists=rows.some(x=>String(x.id)===String(t.item?.id));if(!exists){rows.unshift(t.item);cloudUpsertLead(t.item)}trash.splice(i,1);cloudDeleteTrash(t);saveState();render();renderTrash();toast(exists?'El lead ya estaba restaurado':'Lead restaurado')}
function deleteTrashItem(i){const t=trash[i];if(!t)return;if(!confirm('¿Eliminar definitivamente este lead de la Papelera?'))return;trash.splice(i,1);cloudDeleteTrash(t);saveState();renderTrash();render()}
function restoreAllTrash(){if(!trash.length)return;const existing=new Set(rows.map(x=>String(x.id))),restored=[],oldTrash=[...trash];oldTrash.forEach(t=>{if(t.item&&!existing.has(String(t.item.id))){restored.push(t.item);existing.add(String(t.item.id))}});rows=[...restored,...rows];trash=[];restored.forEach(cloudUpsertLead);oldTrash.forEach(cloudDeleteTrash);saveState();render();renderTrash();toast(`${restored.length} lead(s) restaurados`)}
function emptyTrash(){if(!trash.length)return;if(!confirm(`¿Vaciar definitivamente la Papelera? Se eliminarán ${trash.length} elemento(s).`))return;const old=[...trash];trash=[];old.forEach(cloudDeleteTrash);saveState();renderTrash();render();toast('Papelera vaciada')}
function addRow(r){rows.unshift(r);saveState();cloudUpsertLead(r);render()}
function toast(m){let t=$('toast');t.textContent=m;t.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>t.classList.remove('show'),2200)}
function analyzeText(){let v=$('paste').value.trim();if(!v)return toast('Pegá texto primero');addRow(parse(v));$('paste').value='';$('ph').style.opacity='1';toast('Lead extraído')}
async function processImage(file){$('status').innerHTML='<span class="material-symbols-rounded">hourglass_top</span>Procesando captura...';try{let res=await Tesseract.recognize(file,'spa+eng',{logger:m=>{if(m.status==='recognizing text')$('status').innerHTML=`<span class="material-symbols-rounded">document_scanner</span>Leyendo captura ${Math.round((m.progress||0)*100)}%`}});let txt=res?.data?.text?.trim();if(!txt)throw new Error();addRow(parse(txt));toast('Captura analizada')}catch(e){toast('No pude leer bien esa captura')}finally{$('status').innerHTML='<span class="material-symbols-rounded">check_circle</span>Listo para leer.'}}
function tab(x){$('auto').style.display=x==='auto'?'block':'none';$('manual').style.display=x==='manual'?'block':'none';$('tAuto').classList.toggle('active',x==='auto');$('tManual').classList.toggle('active',x==='manual')}
function addManual(){let n=$('mname').value.trim(),p=$('mphone').value.replace(/\D/g,''),e=$('memail').value.trim();if(!n&&!p&&!e)return toast('Ingresá al menos un dato');addRow({id:Date.now()+Math.random(),nombre:title(n)||'SIN NOMBRE',telefono:p,email:e,provincia:$('mprov').value||province(p),tecnicaturaId:$('mcareer').value,fuente:$('msource').value,observaciones:$('mobs').value,meta:{name:'alta',career:'alta'}});['mname','mphone','memail','mprov','mobs'].forEach(x=>$(x).value='');toast('Lead agregado')}
function leadCopyText(r){const val=(x,fallback='Sin informar')=>String(x||'').trim()||fallback;return [`👤 Nombre: ${val(r.nombre)}`,`📱 Teléfono: ${val(fmtPhone(r.telefono))}`,`✉️ Correo: ${val(r.email)}`,`🎓 Carrera: ${val(CareerMapper[r.tecnicaturaId]?.label)}`,`📍 Provincia: ${val(r.provincia)}`,`📣 Fuente: ${val(r.fuente)}`,`📝 Observaciones: ${val(r.observaciones,'Sin observaciones')}`].join('\n')}
function copyOne(id){let r=rows.find(x=>String(x.id)===String(id));if(!r)return;navigator.clipboard?.writeText(leadCopyText(r));toast('Lead copiado prolijo ✨')}
function copyAll(){if(!rows.length)return toast('No hay leads');navigator.clipboard?.writeText(rows.map((r,i)=>`LEAD ${i+1}\n${leadCopyText(r)}`).join('\n\n────────────────\n\n'));toast(`${rows.length} lead(s) copiados ✨`)}
