function exportExcel(){
  if(!rows.length)return toast('No hay datos');
  const invalidPhone=rows.filter(r=>r.telefono&&String(r.telefono).replace(/\D/g,'').length<10);
  if(invalidPhone.length){toast(`Hay ${invalidPhone.length} teléfono(s) incompletos. Revisalos antes de exportar.`);return;}
  let data=rows.map(r=>({'Nombre Completo':String(r.nombre||'').trim(),'Teléfono':String(r.telefono||'').replace(/\D/g,''),'Email':String(r.email||'').trim(),'Tecnicatura ID':r.tecnicaturaId?String(r.tecnicaturaId):'','Fuente':String(r.fuente||'').trim(),'Provincia':String(r.provincia||'').trim(),'Estado':'sin_contacto','Observaciones':String(r.observaciones||'').trim()}));
  let ws=XLSX.utils.json_to_sheet(data,{cellDates:false});ws['!cols']=[{wch:28},{wch:18},{wch:30},{wch:15},{wch:22},{wch:24},{wch:18},{wch:42}];let wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Leads');XLSX.writeFile(wb,`Leads_CRM_${new Date().toISOString().slice(0,10)}.xlsx`);toast(`Excel generado: ${data.length} lead(s) para CRM`)
}
$('paste').addEventListener('input',()=>{$('ph').style.opacity=$('paste').value.trim()?'0':'1'});$('paste').addEventListener('paste',e=>{let img=[...e.clipboardData.items].find(x=>x.type.startsWith('image/'));if(img){e.preventDefault();processImage(img.getAsFile());return}setTimeout(()=>{if($('paste').value.trim())analyzeText()},40)});$('file').addEventListener('change',e=>{if(e.target.files?.[0])processImage(e.target.files[0]);e.target.value=''});['dragenter','dragover'].forEach(ev=>$('drop').addEventListener(ev,e=>{e.preventDefault();$('drop').classList.add('drag')}));['dragleave','drop'].forEach(ev=>$('drop').addEventListener(ev,e=>{e.preventDefault();$('drop').classList.remove('drag')}));$('drop').addEventListener('drop',e=>{let f=[...e.dataTransfer.files].find(x=>x.type.startsWith('image/'));if(f)processImage(f)});
$('mcareer').innerHTML='<option value="">Sin asignar</option>'+Object.entries(CareerMapper).map(([id,c])=>`<option value="${id}">${c.label} (${c.short})</option>`).join('');
rows=safeRead(STORAGE_KEY,[]);trash=safeRead(TRASH_KEY,[]).map(t=>t.trashId?t:{...t,trashId:'legacy_'+(t.deletedAt||Date.now())+'_'+Math.random().toString(36).slice(2,7)});cleanExpiredTrash();saveState();render();initFirebase();
