const CareerMapper={
1:{label:'Desarrollo web',short:'DW',color:'#b8a68e',words:['desarrollo web','desarrollador web','programacion web','programación web','frontend','backend','full stack','html','css','javascript','react'],codes:['dw','dw-s']},
2:{label:'Administración de empresas',short:'AE',color:'#859f4f',words:['administracion de empresas','administración de empresas','gestion empresarial','gestión empresarial','administracion empresarial','negocios','management','contabilidad'],codes:['ae','ae-s']},
3:{label:'Marketing',short:'MKT',color:'#ff7b1c',words:['marketing','marketing digital','comercializacion','comercialización','publicidad','redes sociales','community manager','branding','social media'],codes:['mkt','mkt-s']},
4:{label:'Higiene y seguridad',short:'HS',color:'#fbc42b',words:['higiene y seguridad','seguridad e higiene','higiene & seguridad','seguridad laboral','prevencion de riesgos','prevención de riesgos'],codes:['hs','hys','h&s','hs-s']},
5:{label:'Gestión inmobiliaria',short:'GI',color:'#be2528',words:['gestion inmobiliaria','gestión inmobiliaria','corredor inmobiliario','martillero','bienes raices','bienes raíces','inmobiliaria','tasacion','tasación','abogacia','abogacía','derecho','legal','juridico','jurídico'],codes:['gi','gi-s']},
6:{label:'Analista de sistemas',short:'AS',color:'#00adef',words:['analista de sistemas','analista sistemas','sistemas informaticos','sistemas informáticos','software','base de datos','sql','informatica','informática'],codes:['as','asc','as-s']},
7:{label:'Ciencia de datos e IA',short:'IA',color:'#405ba8',words:['ciencia de datos e ia','ciencia de datos','inteligencia artificial','data science','data scientist','artificial intelligence','machine learning','deep learning','big data','analista de datos','data analyst'],codes:['ia','ia-hs','cdia','ds','ai']},
8:{label:'Recursos humanos',short:'RRHH',color:'#c397c6',words:['recursos humanos','gestion de recursos humanos','gestión de recursos humanos','capital humano','talento humano','relaciones laborales','reclutamiento','seleccion de personal','selección de personal','liquidacion de sueldos','liquidación de sueldos'],codes:['rrhh','rr hh','rh','rrhh-s']}
};
const prefixes={'11':'CABA, BUENOS AIRES','220':'MERLO, BUENOS AIRES','221':'LA PLATA, BUENOS AIRES','223':'MAR DEL PLATA, BUENOS AIRES','261':'MENDOZA, MENDOZA','264':'SAN JUAN, SAN JUAN','266':'SAN LUIS, SAN LUIS','280':'TRELEW, CHUBUT','291':'BAHIA BLANCA, BUENOS AIRES','294':'BARILOCHE, RIO NEGRO','297':'COMODORO RIVADAVIA, CHUBUT','299':'NEUQUEN, NEUQUEN','341':'ROSARIO, SANTA FE','342':'SANTA FE, SANTA FE','343':'PARANA, ENTRE RIOS','351':'CORDOBA, CORDOBA','3541':'VILLA CARLOS PAZ, CORDOBA','362':'RESISTENCIA, CHACO','370':'FORMOSA, FORMOSA','376':'POSADAS, MISIONES','379':'CORRIENTES, CORRIENTES','380':'LA RIOJA, LA RIOJA','381':'SAN MIGUEL DE TUCUMAN, TUCUMAN','383':'CATAMARCA, CATAMARCA','385':'SANTIAGO DEL ESTERO, SANTIAGO DEL ESTERO','387':'SALTA, SALTA','388':'SAN SALVADOR DE JUJUY, JUJUY'};
const STORAGE_KEY='cargadeleads.rows.v2',TRASH_KEY='cargadeleads.trash.v2',BACKUP_KEY='cargadeleads.backups.v2',LAST_CLEAR_KEY='cargadeleads.lastClear.v2',TRASH_TTL=30*24*60*60*1000;
const firebaseConfig={apiKey:'AIzaSyAfn1RVDfrbNMxVRgOcgHu-8QMmGAhugik',authDomain:'comidassaludables.firebaseapp.com',projectId:'comidassaludables',storageBucket:'comidassaludables.firebasestorage.app',messagingSenderId:'528526969296',appId:'1:528526969296:web:00786114cf5a0f28ab91d5',measurementId:'G-7D62CLX8N0'};
const FIREBASE_LEADS='cargadeleads_leads',FIREBASE_TRASH='cargadeleads_trash';
let rows=[],trash=[],db=null,firebaseReady=false,cloudBusy=false;const $=id=>document.getElementById(id);const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim();const title=s=>String(s||'').trim().toLowerCase().replace(/(^|[\s'-])([a-záéíóúüñ])/g,(_,a,b)=>a+b.toUpperCase());const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function safeRead(key,fallback){try{const v=JSON.parse(localStorage.getItem(key));return v??fallback}catch(e){return fallback}}
function setSaveStatus(msg){if($('saveStatus'))$('saveStatus').textContent=msg}
function saveState(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(rows));localStorage.setItem(TRASH_KEY,JSON.stringify(trash));if(!firebaseReady)setSaveStatus(`💾 Guardado local · ${new Date().toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'})} · Firebase pendiente`);}catch(e){setSaveStatus('⚠️ No se pudo guardar en este navegador')}}
function cleanExpiredTrash(){const now=Date.now();trash=trash.filter(x=>now-(x.deletedAt||now)<TRASH_TTL)}
function createBackup(reason){try{let backups=safeRead(BACKUP_KEY,[]);backups.unshift({createdAt:Date.now(),reason,rows:typeof structuredClone==='function'?structuredClone(rows):JSON.parse(JSON.stringify(rows))});backups=backups.slice(0,10);localStorage.setItem(BACKUP_KEY,JSON.stringify(backups));}catch(e){}}
function cloudId(v){return String(v??'').replace(/[^A-Za-z0-9_.-]/g,'_')||('id_'+Date.now())}
function newTrashEntry(item,reason,clearBatchId=''){return{trashId:'t_'+Date.now()+'_'+Math.random().toString(36).slice(2,9),item,deletedAt:Date.now(),reason,clearBatchId}}
async function initFirebase(){try{if(!firebase.apps.length)firebase.initializeApp(firebaseConfig);db=firebase.firestore();await db.collection(FIREBASE_LEADS).limit(1).get();firebaseReady=true;setSaveStatus('☁️ Firebase conectado · sincronizando…');await loadAndMergeCloud();setSaveStatus(`☁️ Guardado en Firebase + navegador · ${new Date().toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'})}`)}catch(e){firebaseReady=false;console.error('Firebase:',e);setSaveStatus('⚠️ Firebase no disponible · se guarda localmente')}}
async function loadAndMergeCloud(){if(!firebaseReady)return;const [leadSnap,trashSnap]=await Promise.all([db.collection(FIREBASE_LEADS).get(),db.collection(FIREBASE_TRASH).get()]);const remoteRows=leadSnap.docs.map(d=>d.data()?.item).filter(Boolean),remoteTrash=trashSnap.docs.map(d=>({...d.data(),trashId:d.id})).filter(x=>x.item);if(remoteRows.length||remoteTrash.length){const map=new Map(rows.map(r=>[String(r.id),r]));remoteRows.forEach(r=>map.set(String(r.id),r));rows=[...map.values()];const tmap=new Map(trash.map(t=>[t.trashId||('legacy_'+t.deletedAt+'_'+t.item?.id),t]));remoteTrash.forEach(t=>tmap.set(t.trashId,t));trash=[...tmap.values()];cleanExpiredTrash();saveState();render();await syncLocalMissingToCloud()}else if(rows.length||trash.length){await syncLocalMissingToCloud()}}
async function cloudUpsertLead(r){if(!firebaseReady||!r)return;try{await db.collection(FIREBASE_LEADS).doc(cloudId(r.id)).set({item:r,updatedAt:firebase.firestore.FieldValue.serverTimestamp()});setSaveStatus('☁️ Guardado en Firebase + navegador')}catch(e){console.error(e);setSaveStatus('⚠️ Error guardando en Firebase · copia local segura')}}
async function cloudDeleteLead(id){if(!firebaseReady)return;try{await db.collection(FIREBASE_LEADS).doc(cloudId(id)).delete()}catch(e){console.error(e)}}
async function cloudUpsertTrash(t){if(!firebaseReady||!t)return;if(!t.trashId)t.trashId='t_'+Date.now()+'_'+Math.random().toString(36).slice(2,9);try{await db.collection(FIREBASE_TRASH).doc(t.trashId).set({...t,updatedAt:firebase.firestore.FieldValue.serverTimestamp()})}catch(e){console.error(e)}}
async function cloudDeleteTrash(t){if(!firebaseReady||!t?.trashId)return;try{await db.collection(FIREBASE_TRASH).doc(t.trashId).delete()}catch(e){console.error(e)}}
async function syncLocalMissingToCloud(){if(!firebaseReady||cloudBusy)return;cloudBusy=true;try{for(const r of rows)await cloudUpsertLead(r);for(const t of trash)await cloudUpsertTrash(t)}finally{cloudBusy=false}}
async function deleteCollection(name){if(!firebaseReady)return;while(true){const snap=await db.collection(name).limit(300).get();if(snap.empty)break;const batch=db.batch();snap.docs.forEach(d=>batch.delete(d.ref));await batch.commit();if(snap.size<300)break}}
async function purgeAllData(){const total=rows.length+trash.length;if(!total&&!safeRead(BACKUP_KEY,[]).length&&!safeRead(LAST_CLEAR_KEY,null))return toast('No hay datos para borrar');if(!confirm('Esto borrará DEFINITIVAMENTE todos los leads activos, la Papelera, restauraciones y backups locales. También eliminará los datos guardados en Firebase.\n\nEsta acción no se puede deshacer.'))return;const code=prompt('Para confirmar, escribí BORRAR');if(code!=='BORRAR')return toast('Borrado cancelado');setSaveStatus('🧹 Borrando datos…');try{if(firebaseReady)await Promise.all([deleteCollection(FIREBASE_LEADS),deleteCollection(FIREBASE_TRASH)]);rows=[];trash=[];[STORAGE_KEY,TRASH_KEY,BACKUP_KEY,LAST_CLEAR_KEY].forEach(k=>localStorage.removeItem(k));render();setSaveStatus(firebaseReady?'☁️ Firebase y navegador limpios':'💾 Datos locales eliminados');toast('Todos los datos fueron eliminados definitivamente')}catch(e){console.error(e);saveState();setSaveStatus('⚠️ No se pudo completar el borrado en Firebase');toast('Hubo un error al borrar en Firebase')}}
function cleanName(v){let s=String(v||'').replace(/^[^A-Za-zÁÉÍÓÚÜÑáéíóúüñ]+/,'').replace(/[^A-Za-zÁÉÍÓÚÜÑáéíóúüñ' .-]+$/g,'').replace(/\s+/g,' ').trim();if(!s||/\d|@|https?:/i.test(s))return'';const bad=['hola','buenas','buen dia','buenos dias','informacion','información','consulta','mensaje','no es un contacto','ningun grupo en comun','ningún grupo en común','herramientas de seguridad','bloquear','hoy','ayer','viernes','lunes','martes','miercoles','miércoles','jueves','sabado','sábado','domingo','añadir a la lista','anadir a la lista'];if(bad.includes(norm(s)))return'';let w=s.split(/\s+/);if(w.length<1||w.length>5||s.length>55)return'';return title(s)}
function explicitName(raw){const patterns=[/(?:mi\s+)?nombre(?:\s+completo|\s+y\s+apellido)?\s*(?:es)?\s*[:;=\-]?\s*([A-Za-zÁÉÍÓÚÜÑáéíóúüñ' -]{2,70}?)(?=\s*(?:\n|mi\s+consulta|consulta|carrera|inter[eé]s|telefono|teléfono|celular|correo|email|mail|[.!?]|$))/ig,/(?:^|\n|[.!?])\s*(?:hola[!,.;:\s-]*)?(?:soy|me\s+llamo)\s+([A-Za-zÁÉÍÓÚÜÑáéíóúüñ' -]{2,60}?)(?=\s+(?:y\s+(?:quiero|necesito|consulto|me\s+interesa)|consulta|carrera|inter[eé]s|telefono|teléfono|celular|correo|email|mail)\b|[.!?,]|$)/ig];let out=[];for(const r of patterns){let m;while((m=r.exec(raw))){const v=cleanName(m[1]);if(v)out.push(v)}}return out.sort((a,b)=>b.split(' ').length-a.split(' ').length||b.length-a.length)[0]||''}
function whatsappProfileName(raw){const lines=String(raw||'').replace(/\r/g,'').split('\n').map(x=>x.replace(/\s+/g,' ').trim()).filter(Boolean);const stop=/^(no es un contacto|ning[uú]n grupo|herramientas de seguridad|bloquear|hoy|ayer|viernes|lunes|martes|mi[eé]rcoles|jueves|s[aá]bado|domingo|tu empresa usa|haz clic|servicio seguro|a[nñ]adir a la lista)/i;
for(const line of lines.slice(0,35)){const m=line.match(/^[~～˜^`'\-–—.:;·•]+\s*([A-Za-zÁÉÍÓÚÜÑáéíóúüñ][A-Za-zÁÉÍÓÚÜÑáéíóúüñ' .-]{0,50})$/);if(m){const v=cleanName(m[1]);if(v)return v}}
for(let i=0;i<Math.min(lines.length,40);i++){if(!/^no es un contacto/i.test(norm(lines[i])))continue;for(let j=i-1;j>=Math.max(0,i-3);j--){const v=cleanName(lines[j]);if(v)return v}}
const phone=/(?:\+?\s*54\s*9?|\b54\s*9?)?[\s().-]*\d{2,4}(?:[\s().-]*\d{2,4}){2,4}/;for(let i=0;i<Math.min(lines.length,35);i++){if(!phone.test(lines[i]))continue;for(let j=i+1;j<=Math.min(lines.length-1,i+3);j++){if(stop.test(norm(lines[j])))break;const v=cleanName(lines[j]);if(v)return v}}
const flat=String(raw||'').replace(/\n+/g,' ').replace(/\s+/g,' ');const merged=flat.match(/(?:\+?\s*54\s*9?\s*)?(?:\d[\d\s().-]{8,}\d)\s*[~～˜^`'\-–—.:;·•]*\s*([A-Za-zÁÉÍÓÚÜÑáéíóúüñ][A-Za-zÁÉÍÓÚÜÑáéíóúüñ' .-]{1,50}?)(?=\s+(?:no es un contacto|ning[uú]n grupo|herramientas de seguridad|bloquear)\b)/i);if(merged){const v=cleanName(merged[1]);if(v)return v}return''}
function detectName(text,email,source){const raw=String(text||'').replace(/\r/g,'');const ex=explicitName(raw);if(ex)return{name:ex,confidence:'alta'};if(source==='WhatsApp Comercial'){const p=whatsappProfileName(raw);if(p)return{name:p,confidence:'alta'}}if(email){const v=cleanName(email.split('@')[0].replace(/[._-]+/g,' ').replace(/\d+/g,' '));if(v)return{name:v,confidence:'baja'}}return{name:'SIN NOMBRE',confidence:'baja'}}
function detectEmail(t){return (String(t||'').match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/ig)||[])[0]||''}
function normalizePhone(d){let x=String(d||'').replace(/\D/g,'');if(x.startsWith('00549'))x=x.slice(2);if(x.startsWith('0054'))x=x.slice(2);if(x.startsWith('549')&&x.length>=13)return x.slice(0,13);if(x.startsWith('54')&&x.length>=12)return x.slice(0,12);if(x.length===10)return x;if(x.length===12){for(let a=2;a<=4;a++){if(x.slice(a,a+2)==='15'){let z=x.slice(0,a)+x.slice(a+2);if(z.length===10)return z}}}return''}
function detectPhone(t){const raw=String(t||'').replace(/[–—−]/g,'-');let cand=[];const add=(v,s)=>{let n=normalizePhone(v);if(n)cand.push({n,s})};(raw.match(/(?:\+|00)?\s*54\s*[-.]?\s*9?\s*(?:\(?\d{2,4}\)?)(?:[\s.\-]*\d{2,4}){2,4}/g)||[]).forEach(v=>add(v,100));(raw.match(/(?:\+?\d{1,3}[\s.\-]*)?(?:\(?\d{2,4}\)?[\s.\-]*){2,5}\d{2,4}/g)||[]).forEach(v=>add(v,60));cand.sort((a,b)=>b.s-a.s||b.n.length-a.n.length);return cand[0]?.n||''}
function province(p){let x=String(p||'').replace(/\D/g,'');if(x.startsWith('549'))x=x.slice(3);else if(x.startsWith('54'))x=x.slice(2);for(let l=4;l>=2;l--){let k=x.slice(0,l);if(prefixes[k])return prefixes[k]}return''}
function source(t,e){let n=norm(t);if(/whatsapp|meta para administrar este chat|no es un contacto|ningun grupo en comun|ningún grupo en común|herramientas de seguridad|bloquear/.test(n))return'WhatsApp Comercial';if(/(^|\n)\s*(de|from|para|to|asunto|subject)\s*:/i.test(t)||e)return'Correo';if(/instagram|facebook|messenger/.test(n))return'Facebook / Instagram';if(/formulario|landing|sitio web/.test(n))return'Web';return'WhatsApp Comercial'}
function career(t){let n=norm(t),best={id:'',score:0};Object.entries(CareerMapper).forEach(([id,c])=>{let s=0;c.codes.forEach(x=>{let r=new RegExp(`(^|[^a-z0-9])${norm(x).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}([^a-z0-9]|$)`,'i');if(r.test(n))s+=16});c.words.forEach(x=>{if(n.includes(norm(x)))s+=norm(x).split(' ').length>1?10:4});if(s>best.score)best={id,score:s}});return{id:best.score>=7?best.id:'',confidence:best.score>=20?'alta':best.score>=10?'media':best.score>=7?'baja':'baja'}}
function parse(t){let email=detectEmail(t),src=source(t,email),ph=detectPhone(t),nm=detectName(t,email,src),ca=career(t);return{id:Date.now()+Math.random(),nombre:nm.name,telefono:ph,email,provincia:province(ph),tecnicaturaId:ca.id,fuente:src,observaciones:'',meta:{name:nm.confidence,career:ca.confidence}}}
function fmtPhone(p){let x=String(p||'').replace(/\D/g,'');if(x.startsWith('549')&&x.length>=13)return `+54 9 ${x.slice(3,7)} ${x.slice(7,9)}-${x.slice(9,13)}`;if(x.startsWith('54')&&x.length>=12)return `+54 ${x.slice(2,6)} ${x.slice(6,8)}-${x.slice(8,12)}`;return x}
function badge(v){return `<span class="badge ${v||'baja'}">${v==='alta'?'Alta':v==='media'?'Media':'Revisar'}</span>`}
